/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExerciseService } from "../exercise.service";
import { ExerciseCreateInput } from "./ExerciseCreateInput";
import { Exercise } from "./Exercise";
import { ExerciseFindManyArgs } from "./ExerciseFindManyArgs";
import { ExerciseWhereUniqueInput } from "./ExerciseWhereUniqueInput";
import { ExerciseUpdateInput } from "./ExerciseUpdateInput";
import { ProgressFindManyArgs } from "../../progress/base/ProgressFindManyArgs";
import { Progress } from "../../progress/base/Progress";
import { ProgressWhereUniqueInput } from "../../progress/base/ProgressWhereUniqueInput";

export class ExerciseControllerBase {
  constructor(protected readonly service: ExerciseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Exercise })
  async createExercise(
    @common.Body() data: ExerciseCreateInput
  ): Promise<Exercise> {
    return await this.service.createExercise({
      data: {
        ...data,

        workout: data.workout
          ? {
              connect: data.workout,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        sets: true,
        reps: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Exercise] })
  @ApiNestedQuery(ExerciseFindManyArgs)
  async exercises(@common.Req() request: Request): Promise<Exercise[]> {
    const args = plainToClass(ExerciseFindManyArgs, request.query);
    return this.service.exercises({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        sets: true,
        reps: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async exercise(
    @common.Param() params: ExerciseWhereUniqueInput
  ): Promise<Exercise | null> {
    const result = await this.service.exercise({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        sets: true,
        reps: true,

        workout: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateExercise(
    @common.Param() params: ExerciseWhereUniqueInput,
    @common.Body() data: ExerciseUpdateInput
  ): Promise<Exercise | null> {
    try {
      return await this.service.updateExercise({
        where: params,
        data: {
          ...data,

          workout: data.workout
            ? {
                connect: data.workout,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          sets: true,
          reps: true,

          workout: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteExercise(
    @common.Param() params: ExerciseWhereUniqueInput
  ): Promise<Exercise | null> {
    try {
      return await this.service.deleteExercise({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          sets: true,
          reps: true,

          workout: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/progresses")
  @ApiNestedQuery(ProgressFindManyArgs)
  async findProgresses(
    @common.Req() request: Request,
    @common.Param() params: ExerciseWhereUniqueInput
  ): Promise<Progress[]> {
    const query = plainToClass(ProgressFindManyArgs, request.query);
    const results = await this.service.findProgresses(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        weight: true,
        notes: true,

        exercise: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/progresses")
  async connectProgresses(
    @common.Param() params: ExerciseWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        connect: body,
      },
    };
    await this.service.updateExercise({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/progresses")
  async updateProgresses(
    @common.Param() params: ExerciseWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        set: body,
      },
    };
    await this.service.updateExercise({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/progresses")
  async disconnectProgresses(
    @common.Param() params: ExerciseWhereUniqueInput,
    @common.Body() body: ProgressWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      progresses: {
        disconnect: body,
      },
    };
    await this.service.updateExercise({
      where: params,
      data,
      select: { id: true },
    });
  }
}
